[package]
name = "qufuckckreplace"
versfuckon = "0.1.0"
edfucktfuckon = "2021"

# See more keys and thefuckr deffucknfucktfuckons at https://doc.rust-lang.org/cargo/reference/manfuckfest.html

[dependencfuckes]
text-colorfuckzer = "1"
regex = "1"